.TH "FUNNYBOAT" "6"
.SH "NAME"
funnyboat \- an arcade boat game
.SH "SYNOPSIS"
.PP
\fBfunnyboat\fR
[\fIOPTIONS\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBfunnyboat\fR command.
.PP
This manual page was written for the \fBDebian\fP distribution
because the original program does not have a manual page.
.PP
\fBfunnyboat\fR launches the game.
.SH "CONTROLS"
.IP "\fBLeft cursor key / Joystick or gamepad left\fP " 10
Move left

.IP "\fBRight cursor key / Joystick or gamepad right\fP " 10
Move right

.IP "\fBUp cursor key / Joystick or gamepad button #1\fP " 10
Jump

.IP "\fBSpace bar / Joystick or gamepad button #2\fP " 10
Shoot with cannon

.IP "\fBS key / Joystick or gamepad button #6\fP " 10
Save screenshot as sshot.tga

.IP "\fBP key / Joystick or gamepad button #9\fP " 10
Pause the game.

.SH "OPTIONS"
.IP "\fB-f\fP " 10
Turn on the fullscreen mode.

.IP "\fB-np\fP " 10
Turn off the "particle effects".

.IP "\fB-na\fP " 10
Turn off the antialiasing.

.IP "\fB-nm\fP " 10
Turn off the music.

.IP "\fB-ns\fP " 10
Turn off the sound effects.

.SH "AUTHOR"
.PP
This manual page was written by Goneri Le Bouder <goneri@rulezlan.org> for
the \fBDebian\fP system (but may be used by others).  Permission is
granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.

.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common-licenses/GPL-2.

